service: my-express-app-test

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  httpApi:
    useHttp: true
    
functions:
  api:
    handler: src/index.main
    events:
      - http:
          path: /
          method: ANY
