

service: my-express-app
frameworkVersion: '2 || 3'


provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  api:
    handler: /src/index.handler
      events:
      - httpApi: '*'
      